#!/bin/bash

conda activate func_anno "python=3.11" funannotate

############# FUNANNOTATE INSTALLATION #############

# setup funannotate databases
funannotate setup -b metazoa -d funannotate_DB/
export FUNANNOTATE_DB=/path/to/funannotate_DB/

# Download GeneMark-ES/ET/EP+ ver 4.71_lic and key from http://topaz.gatech.edu/GeneMark/license_download.cgi
tar -xf gmes_linux_64.tar.gz
mkdir gm_key
cp -r gm_key_64.gz gm_key/

# locate perl
which perl

# change all script perl tag from gmes folder 
cd gmes/
perl change_path_in_perl_scripts.pl 'perl PATH'

# set the path for GeneMark using 
export GENEMARK_PATH=$PWD/gmes/

# making sure that gmes_petap.pl in the PATH using 
export PATH=$PATH:$PWD/gmes/

######################################################

# Phobius (download from https://software.sbc.su.se/phobius.html)
phobius.pl -short Phar.braker.prot.fasta > Phar.phobius.results.txt

# InterProScan
funannotate iprscan -i Phar.braker.prot.fasta -m docker -c 50-o Phar_iprscan.xml

# eggnog-mapper
emapper.py --cpu 50 -m mmseqs --data_dir funannotate_DB  -i Phar.braker.prot.fasta -o Phar_eggnog

# # FUNANNOTATE ANNOTATE # #
funannotate annotate --gff PAG_Phar_UKon_1.1.gff3 --fasta PAG_UKon_Phar_1.1.fasta -s "Porites harrisoni" --busco_db  metazoa --eggnog Phar_eggnog.emapper.annotations --iprscan Phar_iprscan.xml --phobius phobius.results.txt --cpus 100 -o braker_anno

########## NCBI SUBMISSION ############ 

# this is only if you plan to submit to NCBI #
table2asn -M n -J -c w -euk -t Phar_ncbi.sbt -i PAG_UKon_Phar_1.1.fasta -gaps-min 10 -l paired-ends -j "[organism=Porites harrisoni] [isolate=UAE_SA_Phar_3_34-1_1080]" -locus-tag-prefix ABFA07 -f PAG_Phar_UKon_1.1.gff3 -o PAG_UKon_Phar.sqn -Z

#######################################


# # CHECK FINAL STATS # #
# this is generated by funannotate directly, but if you have done any manual curation of the gff3 file afterwards, you can run this again:
funannotate util stats -f /path/to/necat/PAG_Phar_UKon_1.1.fasta -g PAG_Phar_UKon_1.1.gff3 -o PAG_Phar_UKon_1.1.json
